# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Build type-morph binary
      run: make build

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
